### ISSUE TITLE
value | is not a member of String in Scala 2.10

### ISSUE THREAD

**Issue by thesamet** [lihaoyi/fastparse#72]
It seems that the ParserApi implicit does not get invoked in Scala 2.10. The same source code compiles with Scala 2.11.

Sample build.sbt:

```
scalaVersion := "2.10.6"

libraryDependencies += "com.lihaoyi" %% "fastparse" % "0.3.4"
```

Hello.scala:

```
import fastparse.all._

object Hello {
  val t: P[String] = P("boo" | "bar")
}
```

`sbt compile`:

```
[info] Compiling 1 Scala source to /tmp/fp/target/scala-2.10/classes...
[error] /tmp/fp/Hello.scala:4: value | is not a member of String
[error]   val t: P[String] = P("boo" | "bar")
[error]                              ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 1 s, completed Dec 27, 2015 5:36:13 PM
```

**Comment by thesamet** [comment]
Found a workaround. I am mixing in the following trait in all objects that use fastparse combinators:

```
trait Scala210Compat {
  protected implicit def strToParserApi(s: String): ParserApi[Unit] = parserApi(s)
  protected implicit def parserToParserApi[T](s: Parser[T]): ParserApi[T] = parserApi(s)
}
```

**Comment by capacman** [comment]
Same thing with scala 2.10.6. I just copied example json parser and try to run it

Error:(40, 36) No implicit view available from fastparse.parsers.Intrinsics.CharsWhile => fastparse.core.Parser[V].
  val space         = P( CharsWhile(Whitespace).? )
                                   ^

**Comment by YoEight** [comment]
Also got the same issue with `0.3.7` version. Thanks @thesamet for the workaround !

**Comment by jrpelkonen** [comment]
I had the same issue. I fixed it by including macro paradise as it does not come with Scala 2.10. Basically, for Scala 2.10.6 this works, for other versions of scala 2.10, tweaks may be needed:

```
libraryDependencies ++= Seq(
  ...
  "com.lihaoyi" %% "fastparse" % "0.3.7",
  compilerPlugin("org.scalamacros" % "paradise" % "2.0.1" cross CrossVersion.full),
...
```

**Comment by cjuexuan** [comment]
if  using maven ? how to solve this problem?

**Comment by lihaoyi** [comment]
Probably going to call this `wontfix`; most people should have upgraded to 2.11, and if you're still on 2.10 upgrading is probably the higher priority
